### ISSUE TITLE
problems with certain routes

### ISSUE THREAD

**Issue by deanmalmgren** [deanmalmgren/marey-metra#10]
This is a little bit of a placeholder, but I'd like to get a sense of whether this is a network-type of an issue or whether there is something consistently broken with some of the routes. I'm getting [emails](https://mail.google.com/mail/u/0/#search/cron+marey-metra+There+are+no+trains+available+for+the+selected+stops) that look like the following for lots of trains:

```
Exception raised when querying the rail time tracker for trip UP-W_UW10_V1 traveling from ELBURN to OTC.

Response (200) back from server:

{
  "train1": {
    "error": "There are no trains available for the selected stops.  Please change your search and try again.",
    "status": 0
  }
}
```

Looking at the dates on which we get this error, it appears to be intermittent. Probably we need some better error handling in this situation so we can diagnose what's going on. Might be good to add the `tracked_times` to the error message.
- UP-W_UW10_V1 : 2/2 2/5 2/6
- UP-W_UW11_V1 OTC to ELBURN: 2/6
- UP-W_UW53_V1 KEDZIE to ELBURN: 2/2 2/5
- UP-W_UW73_V1 MELROSEPK to ELBURN: 2/6
- UP-W_UW70_V1 ELBURN to OTC: 2/6
- UP-W_UW68_V1 BERKELEY to OTC: 2/5

**Comment by deanmalmgren** [comment]
Train 10 doesn't start until 4:48. Perhaps all of these routes are starting early for some reason...

```
Script started at 2015-02-24 03:43:02.032997.
Exception raised when querying the rail time tracker for trip UP-W_UW10_V1 traveling from ELBURN to OTC.

                ELBURN                  None                  None
                 LAFOX                  None                  None
                GENEVA                  None                  None
              WCHICAGO                  None                  None
              WINFIELD                  None                  None
               WHEATON                  None                  None
            COLLEGEAVE                  None                  None
             GLENELLYN                  None                  None
               LOMBARD                  None                  None
             VILLAPARK                  None                  None
              ELMHURST                  None                  None
              BERKELEY                  None                  None
              BELLWOOD                  None                  None
             MELROSEPK                  None                  None
               MAYWOOD                  None                  None
            RIVRFOREST                  None                  None
               OAKPARK                  None                  None
                KEDZIE                  None                  None
                   OTC                  None                  None



Response (200) back from server:

{
  "train1": {
    "error": "There are no trains available for the selected stops.  Please change your search and try again.",
    "status": 0
  }
}



--------------------------------------------------------------------------------

Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/srv/www/marey-metra/web/base/management/commands/query_rail_time_tracker.py", line 65, in handle
    self.query_all_trains()
  File "/srv/www/marey-metra/web/base/management/commands/query_rail_time_tracker.py", line 91, in query_all_trains
    raise e
KeyError: 'train_num'
```
